"""Database module for DrSpec."""

from __future__ import annotations

from drspec.db.connection import get_connection, init_schema
from drspec.db.queries import (
    Artifact,
    QueueItem,
    VisionFinding,
    ContractDetails,
    VALID_ARTIFACT_STATUSES,
    VALID_QUEUE_STATUSES,
    VALID_QUEUE_REASONS,
    VALID_FINDING_TYPES,
    VALID_FINDING_SIGNIFICANCE,
    VALID_FINDING_STATUSES,
    insert_artifact,
    get_artifact,
    list_artifacts,
    count_artifacts,
    update_artifact_status,
    insert_contract,
    get_contract,
    list_contracts,
    count_contracts,
    get_contract_confidence_stats,
    query_contract,
    query_contracts,
    search_contracts,
    queue_push,
    queue_pop,
    queue_peek,
    queue_get,
    queue_complete,
    queue_retry,
    queue_prioritize,
    queue_remove,
    queue_count,
    queue_clear_completed,
    insert_dependency,
    get_callers,
    get_callees,
    insert_reasoning_trace,
    get_reasoning_traces,
    get_config,
    set_config,
    get_all_config,
    insert_vision_finding,
    get_vision_findings,
    get_all_vision_findings,
    update_vision_finding_status,
    count_vision_findings,
    calculate_confidence_with_findings,
)
from drspec.db.graph import (
    DependencyNode,
    DependencyEdge,
    DependencyGraph,
    get_dependency_graph,
    get_callee_graph,
    get_caller_graph,
    get_graph_statistics,
)

__all__ = [
    # Connection
    "get_connection",
    "init_schema",
    # Models
    "Artifact",
    "QueueItem",
    "VisionFinding",
    "ContractDetails",
    # Constants
    "VALID_ARTIFACT_STATUSES",
    "VALID_QUEUE_STATUSES",
    "VALID_QUEUE_REASONS",
    "VALID_FINDING_TYPES",
    "VALID_FINDING_SIGNIFICANCE",
    "VALID_FINDING_STATUSES",
    # Artifact queries
    "insert_artifact",
    "get_artifact",
    "list_artifacts",
    "count_artifacts",
    "update_artifact_status",
    # Contract queries
    "insert_contract",
    "get_contract",
    "list_contracts",
    "count_contracts",
    "get_contract_confidence_stats",
    # Contract query functions (for Debugger Agent)
    "query_contract",
    "query_contracts",
    "search_contracts",
    # Queue queries
    "queue_push",
    "queue_pop",
    "queue_peek",
    "queue_get",
    "queue_complete",
    "queue_retry",
    "queue_prioritize",
    "queue_remove",
    "queue_count",
    "queue_clear_completed",
    # Dependency queries
    "insert_dependency",
    "get_callers",
    "get_callees",
    # Reasoning trace queries
    "insert_reasoning_trace",
    "get_reasoning_traces",
    # Config queries
    "get_config",
    "set_config",
    "get_all_config",
    # Vision finding queries
    "insert_vision_finding",
    "get_vision_findings",
    "get_all_vision_findings",
    "update_vision_finding_status",
    "count_vision_findings",
    "calculate_confidence_with_findings",
    # Graph models
    "DependencyNode",
    "DependencyEdge",
    "DependencyGraph",
    # Graph queries
    "get_dependency_graph",
    "get_callee_graph",
    "get_caller_graph",
    "get_graph_statistics",
]
